In [1]:
n=[1,2,3,4,5,5,5,5,5]
print(n.count(5))

5


In [3]:
n=[1,2,3,4,5]
n.insert(1,888)
print(n)

[1, 888, 2, 3, 4, 5]


In [5]:
n=[1,2,3]
b=[4,5,6]
n.extend(b)
print(n)

[1, 2, 3, 4, 5, 6]


In [7]:
n=[1,2,3]
n.append(4)
print(n)

[1, 2, 3, 4]


In [10]:
n=[1,2,3,4,5]
n.remove(2)
print(n)

[1, 3, 4, 5]


n.pop()
print(n)

In [11]:
n=[1,2,3,4]
n.pop()
print(n)

[1, 2, 3]


In [12]:
n=[1,2,3,4]
n.reverse()
print(n)

[4, 3, 2, 1]


In [13]:
n=['mythri','nivi','pooja','nami']
n.sort()
print(n)


['mythri', 'nami', 'nivi', 'pooja']


In [14]:
n=['mythri','nivi','pooja','nami']
n.sort(reverse=True)
print(n)

['pooja', 'nivi', 'nami', 'mythri']


In [16]:
x=[1,2,3,4]
y=x
y[1]=777
print(x)
print(y)

[1, 777, 3, 4]
[1, 777, 3, 4]


In [17]:
x=[1,2,3,4]
y=x[:]
y[1]=777
print(x)
print(y)

[1, 2, 3, 4]
[1, 777, 3, 4]


In [18]:
x=[1,2,3,4]
y=x.copy()
y[1]=777
print(x)
print(y)

[1, 2, 3, 4]
[1, 777, 3, 4]


In [21]:
a=[10,20,30]
b=[40,50,60]
c=a+b
print(c)
x=[10,20,30]
y=x*3
print(y)

[10, 20, 30, 40, 50, 60]
[10, 20, 30, 10, 20, 30, 10, 20, 30]


In [24]:
x=["MITE","MANGLORE","NITTE"]
y=["MITE","MANGLORE","NITTE"]
x==y
x!=y
z=["MITE","MANGLORE","NITTE"]
x==z

True

In [25]:
m=[10,20,30,40,[50,60,70]]
m[3]
m[4][1]
m.clear()
n=[1,2,3,4]
print(4 in n)


True


In [26]:
s=[2**x for x in range(1,6)]
print(s)

[2, 4, 8, 16, 32]


In [27]:
words=["MITE","Mysore","Anubhav"]
l=[w[0] for w in words]
print(l)

['M', 'M', 'A']


In [36]:
    return var*2
seq=[1,2,3,4,5]
list(map(times2,seq))

[2, 4, 6, 8, 10]

In [37]:
seq=[1,2,3,4]
lambda var: var*2
list(map(lambda var: var*2,seq))
list(filter(lambda item:item%2==0,seq))

[2, 4]

In [2]:
import numpy as np



[1, 2, 3]

In [3]:
my_list=[1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arrange(0,10)

AttributeError: module 'numpy' has no attribute 'arrange'

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(3,3)

TypeError: data type not understood

In [13]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(2)

array([0.40009403, 0.77370471])

In [17]:
np.random.rand(5,5)

array([[0.39505915, 0.40119646, 0.48680931, 0.03780622, 0.66804431],
       [0.85303763, 0.18021712, 0.36921902, 0.88765627, 0.38656481],
       [0.93381769, 0.93935038, 0.54282037, 0.41863966, 0.54097436],
       [0.74728862, 0.95072711, 0.81145272, 0.66407931, 0.1388094 ],
       [0.01344533, 0.79218609, 0.84868844, 0.63845677, 0.96530822]])

In [18]:
np.random.randn(5,5)

array([[-2.58959271, -0.83804959,  0.6013422 ,  0.18813463,  0.81184571],
       [-0.00933172, -0.1162868 , -0.19834993, -0.54641823,  1.04014202],
       [ 1.54592288,  1.92971207, -1.4659614 , -0.87583351,  1.64812728],
       [-0.65813633, -0.89795361,  0.28115046,  0.12419002,  1.71379557],
       [ 0.81459536,  0.47025836, -0.36576673, -0.50164148,  1.59200438]])

In [19]:
np.random.randint(1,100,1)

array([96, 41, 65, 74, 73, 12, 96, 28, 29, 76])

In [20]:
arr=np.arrange(24)

AttributeError: module 'numpy' has no attribute 'arrange'

In [24]:
arr=np.arange(25)

In [22]:
runarr=np.random.randint(0,50,10)

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
runarr.max()

49

In [28]:
runarr.argmax()

0

In [30]:
argmin and min

NameError: name 'argmin' is not defined

In [31]:
arr.shape

(25,)

In [32]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [33]:
arr.reshape(1,25).shape

(1, 25)

In [34]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [35]:
arr.reshape(25,1).shape

(25, 1)

In [36]:
arr.dtype

dtype('int32')

In [37]:
arr=np.arange(0,10)

In [38]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [41]:
arr/arr

E:\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [43]:
1/arr

E:\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [44]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [45]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [46]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [47]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [48]:
np.log(arr)

E:\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [49]:
arr=np.arange(0,11)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr[8]

8

In [52]:
arr[1:15]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr[0:5]=100

In [54]:
arr=np.arange(0,11)

In [55]:
arr>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [56]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr